package aplicacion.modelo.dominio;
// Generated 12/06/2018 23:06:23 by Hibernate Tools 4.3.1


import aplicacion.modelo.dominio.Usuario;
import java.util.Date;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer codigo;
     private Usuario usuario;
     private String apellidos;
     private String nombres;
     private String dni;
     private Date fechaNac;
     private String email;
     private String direccion;
     private String telefono;

    public Perfil() {
        this.usuario = new Usuario();
    }

    public Perfil(Usuario usuario, String perApellidos, String perNombres, String perDni, Date perFechaNac, String perEmail, String perDireccion, String perTelefono) {
       this.usuario = usuario;
       this.apellidos = perApellidos;
       this.nombres = perNombres;
       this.dni = perDni;
       this.fechaNac = perFechaNac;
       this.email = perEmail;
       this.direccion = perDireccion;
       this.telefono = perTelefono;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


