package aplicacion.modelo.dominio;
// Generated 07-jun-2018 19:46:26 by Hibernate Tools 4.3.1

import java.io.Serializable;




/**
 * Usuarios generated by hbm2java
 */
public class Usuario  implements Serializable {


     private Integer codigo;
     private String nombreUsuario;
     private String password;
     private String tipoUsuario;
     private boolean estado;

    public Usuario() {
    }

    public Usuario(Integer codigo, String nombreUsuario, String password, String tipoUsuario, boolean estado) {
        this.codigo = codigo;
        this.nombreUsuario = nombreUsuario;
        this.password = password;
        this.tipoUsuario = tipoUsuario;
        this.estado = estado;
    }


   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }



    @Override
    public String toString(){
        return String.format("Usuario[%d,%s]", codigo, nombreUsuario);
    }

       @Override
    public boolean equals(Object other) {
        return (other instanceof Usuario) && (codigo != null)
            ? codigo.equals(((Usuario) other).codigo)
            : (other == this);
    }

    @Override
    public int hashCode() {
        return (codigo != null)
            ? (this.getClass().hashCode() + codigo.hashCode())
            : super.hashCode();
    }
 

}


